spring:
  data:
    mongodb:
      host: localhost
      database: petstore
  application:
    name: ps-pet
server:
  servlet:
    context-path: /ps-pet
  port: 10011
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
